version: "3"
services:
    web:
        image: nginx
        depends_on:
            - app
        volumes:
            - ./web/settings/default.conf:/etc/nginx/conf.d/default.conf
            - ./php/src/:/var/www/html
        ports:
            - "8081:80"
    app:
        image: php:8-fpm
        volumes:
            - ./php/src/:/var/www/html
            - ./php/settings/php.ini:/usr/local/etc/php/php.ini
