name: EC2 pull

on:
 pull_request:
   branches: [ main ]
   types: [closed]

 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:

     # BranchをCheckout
     - name: Checkout
       uses: actions/checkout@v2

     # デプロイする
     - name: Deploy
       run: |

         # SSH接続して、git pullする
         echo "${{ secrets.GIT_PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -i private_key ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -t "cd /home/ec2-user/playground/tanzu-demo && git checkout main && git pull"
         # ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -i private_key "cd /home/ec2-user/playground/tanzu-demo && git checkout main && git pull"
